// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"ThaiFontAutoAdjuster","status":true,"description":"ปรับตัวอักษรภาษาไทยไปตามยถากรรม\nLicense: MIT License","parameters":{}},
{"name":"NoGameover","status":true,"description":"If you lose in a battle, the game is not over.","parameters":{"Switch ID":"40"}}
];
